// strats/live_strategy_engine.hpp - Multi-strategy live trading engine
#pragma once
#include <memory>
#include <vector>
#include <map>
#include <string>
#include <iostream>
#include "../pipeline/normalized_data.hpp"
#include "../core/order_book.hpp"

namespace strats {

// Trading signal generated by strategy
struct TradingSignal {
    std::string strategy_name;
    std::string exchange;
    std::string product_id;
    std::string side;  // "BUY", "SELL", "CLOSE"
    double size;
    double price;
    double confidence;
    std::chrono::system_clock::time_point timestamp;
    
    std::string to_string() const {
        return "[SIGNAL] " + strategy_name + " | " + 
               exchange + ":" + product_id + " | " +
               side + " " + std::to_string(size) + " @ " + 
               std::to_string(price) + " (conf: " + 
               std::to_string(confidence) + ")";
    }
};

// Base interface for live strategies
class LiveStrategy {
public:
    virtual ~LiveStrategy() = default;
    
    // Called when new quote arrives
    virtual void on_quote(const pipeline::NormalizedQuote& quote) = 0;
    
    // Called when new trade arrives
    virtual void on_trade(const pipeline::NormalizedTrade& trade) {}
    
    // Get any pending signals
    virtual std::vector<TradingSignal> get_signals() = 0;
    
    // Get strategy name
    virtual std::string name() const = 0;
};

// Wrapper to adapt backtest strategies to live trading
class BacktestStrategyAdapter : public LiveStrategy {
public:
    BacktestStrategyAdapter(const std::string& name,
                           const std::string& exchange,
                           const std::string& product)
        : name_(name), exchange_(exchange), product_(product), 
          position_(0), tick_count_(0) {}
    
    void on_quote(const pipeline::NormalizedQuote& quote) override {
        // Update order book
        if (quote.bids.size() > 0 && quote.asks.size() > 0) {
            book_.bids.clear();
            book_.asks.clear();
            
            for (const auto& [price, size] : quote.bids) {
                book_.bids[price] = size;
            }
            for (const auto& [price, size] : quote.asks) {
                book_.asks[price] = size;
            }
            
            tick_count_++;
            check_for_signals(quote);
        }
    }
    
    std::vector<TradingSignal> get_signals() override {
        std::vector<TradingSignal> signals;
        signals.swap(pending_signals_);
        return signals;
    }
    
    std::string name() const override { return name_; }

protected:
    void add_signal(const std::string& side, double size, double price, double conf = 1.0) {
        TradingSignal signal;
        signal.strategy_name = name_;
        signal.exchange = exchange_;
        signal.product_id = product_;
        signal.side = side;
        signal.size = size;
        signal.price = price;
        signal.confidence = conf;
        signal.timestamp = std::chrono::system_clock::now();
        
        pending_signals_.push_back(signal);
    }
    
    virtual void check_for_signals(const pipeline::NormalizedQuote& quote) = 0;
    
    std::string name_;
    std::string exchange_;
    std::string product_;
    core::OrderBook book_;
    int position_;
    uint64_t tick_count_;
    std::vector<TradingSignal> pending_signals_;
};

// Live Imbalance Strategy
class LiveImbalanceStrategy : public BacktestStrategyAdapter {
public:
    LiveImbalanceStrategy(const std::string& exchange, 
                         const std::string& product,
                         double threshold = 0.6,
                         int hold_ticks = 150)
        : BacktestStrategyAdapter("ImbalanceTaker", exchange, product),
          threshold_(threshold), hold_ticks_(hold_ticks),
          state_(0), ticks_left_(0) {}

protected:
    void check_for_signals(const pipeline::NormalizedQuote& quote) override {
        double imbalance = book_.top_imbalance();
        if (std::isnan(imbalance)) return;
        
        if (ticks_left_ > 0) --ticks_left_;
        
        // Check for exit
        if (state_ != 0 && ticks_left_ == 0) {
            add_signal("CLOSE", std::abs(state_), quote.mid_price());
            state_ = 0;
            return;
        }
        
        // Check for reversal
        if (state_ > 0 && imbalance < -threshold_) {
            add_signal("SELL", 2.0, quote.best_bid);
            state_ = -1;
            ticks_left_ = hold_ticks_;
        } else if (state_ < 0 && imbalance > threshold_) {
            add_signal("BUY", 2.0, quote.best_ask);
            state_ = 1;
            ticks_left_ = hold_ticks_;
        }
        
        // Check for entry
        if (state_ == 0) {
            if (imbalance > threshold_) {
                add_signal("BUY", 1.0, quote.best_ask);
                state_ = 1;
                ticks_left_ = hold_ticks_;
            } else if (imbalance < -threshold_) {
                add_signal("SELL", 1.0, quote.best_bid);
                state_ = -1;
                ticks_left_ = hold_ticks_;
            }
        }
    }

private:
    double threshold_;
    int hold_ticks_;
    int state_;
    int ticks_left_;
};

// Live Strategy Engine - manages multiple strategies
class LiveStrategyEngine {
public:
    // Add a strategy
    void add_strategy(std::unique_ptr<LiveStrategy> strategy) {
        std::cout << "[ENGINE] Added strategy: " << strategy->name() << "\n";
        strategies_.push_back(std::move(strategy));
    }
    
    // Process incoming quote (called by subscriber)
    void on_quote(const pipeline::NormalizedQuote& quote) {
        for (auto& strategy : strategies_) {
            strategy->on_quote(quote);
        }
        stats_.quotes_processed++;
    }
    
    // Process incoming trade
    void on_trade(const pipeline::NormalizedTrade& trade) {
        for (auto& strategy : strategies_) {
            strategy->on_trade(trade);
        }
        stats_.trades_processed++;
    }
    
    // Collect all signals from all strategies
    std::vector<TradingSignal> get_signals() {
        std::vector<TradingSignal> all_signals;
        
        for (auto& strategy : strategies_) {
            auto signals = strategy->get_signals();
            all_signals.insert(all_signals.end(), signals.begin(), signals.end());
            stats_.signals_generated += signals.size();
        }
        
        return all_signals;
    }
    
    // Get statistics
    struct Stats {
        uint64_t quotes_processed = 0;
        uint64_t trades_processed = 0;
        uint64_t signals_generated = 0;
    };
    
    Stats get_stats() const { return stats_; }
    
    size_t num_strategies() const { return strategies_.size(); }

private:
    std::vector<std::unique_ptr<LiveStrategy>> strategies_;
    Stats stats_;
};

} // namespace strats
