// sim/matching_engine.hpp - Price-time priority matching engine
// -----------------------------------------------------------------------------
// OVERVIEW:
// - This file implements a simple, high-performance price-time priority
//   matching engine intended for use inside the exchange simulator (sim/).
// - It supports limit orders, market orders, IOC/FOK behavior, partial fills,
//   order cancellation, and maker/taker fees.
// - The engine exposes callback hooks so the caller (the ExchangeSimulator
//   or a test harness) can be notified of fills and order state updates.
// - The engine is intentionally minimal and optimized for single-threaded
//   access (no internal locking). If you must access the engine concurrently
//   from multiple threads, protect it with an external mutex per product.
//
// KEY TYPES & DATA STRUCTURES:
// - Order: simple stateful order object (id, price, size, side, state)
// - Fill: execution event generated by matching results
// - PriceLevel: tracks an in-memory FIFO queue of orders for a single price
// - OrderBookSide: map<price,PriceLevel> representing bids or asks
// - MatchingEngine: contains bids_ and asks_, order lookup map, and next ids
//
// PERFORMANCE & THREADING:
// - This implementation is not thread-safe; callers should use a mutex when
//   accessing MatchingEngine from multiple threads. The ExchangeSimulator
//   currently calls submit_order() and get_snapshot() from different threads
//   in some designs — protect those calls with a per-product mutex.
// - The engine avoids heavy allocations where possible; consider using a
//   memory pool if you have a very high rate of order churn.
//
// INTEGRATION POINTS:
// - To use the engine in the HFT pipeline, obtain L2 snapshots with
//   get_snapshot(), convert them into `pipeline::NormalizedQuote`, and push
//   into your local SPSC/MPMC queue or broadcast via ZeroMQ.
// - For paper trading, call submit_order()/cancel_order() in response to
//   strategy signals and handle fills via the registered fill callback.
//
// SAMPLE USAGE:
// MatchingEngine engine("BTC-USD");
// engine.set_fill_callback([](const Fill& f){ /* route to strategy or logger */ });
// auto order = engine.submit_order("client-1", OrderSide::BUY, OrderType::LIMIT, 50000.0, 0.1);
// auto snap = engine.get_snapshot(10);
// -----------------------------------------------------------------------------

#pragma once

#include "order.hpp"
#include <map>
#include <queue>
#include <vector>
#include <memory>
#include <functional>
#include <algorithm>
#include <random>

namespace sim {

// Price level in order book
struct PriceLevel {
    double price;
    double total_size;
    std::queue<std::shared_ptr<Order>> orders;  // FIFO queue for time priority
    
    PriceLevel(double p) : price(p), total_size(0.0) {}
    
    void add_order(std::shared_ptr<Order> order) {
        orders.push(order);
        total_size += order->remaining_size;
    }
    
    void remove_size(double size) {
        total_size -= size;
    }
};

// Order book side (bid or ask)
class OrderBookSide {
public:
    using PriceLevelMap = std::map<double, PriceLevel>;
    
    OrderBookSide(bool is_bid) : is_bid_(is_bid) {}
    
    // Add order to book
    void add_order(std::shared_ptr<Order> order) {
        double price = order->price;
        
        auto it = levels_.find(price);
        if (it == levels_.end()) {
            it = levels_.emplace(price, PriceLevel(price)).first;
        }
        
        it->second.add_order(order);
    }
    
    // Remove order from book
    bool remove_order(const std::string& order_id) {
        for (auto& [price, level] : levels_) {
            // Linear search through orders at this price level
            // (In production, maintain order_id -> price mapping for O(1) lookup)
            std::queue<std::shared_ptr<Order>> temp_queue;
            bool found = false;
            
            while (!level.orders.empty()) {
                auto order = level.orders.front();
                level.orders.pop();
                
                if (order->order_id == order_id) {
                    level.remove_size(order->remaining_size);
                    found = true;
                } else {
                    temp_queue.push(order);
                }
            }
            
            level.orders = temp_queue;
            
            // Remove empty price level
            if (level.total_size <= 1e-8) {
                levels_.erase(price);
            }
            
            if (found) return true;
        }
        return false;
    }
    
    // Get best price (highest bid / lowest ask)
    double best_price() const {
        if (levels_.empty()) return 0.0;
        return is_bid_ ? levels_.rbegin()->first : levels_.begin()->first;
    }
    
    // Get total size at best price
    double best_size() const {
        if (levels_.empty()) return 0.0;
        return is_bid_ ? levels_.rbegin()->second.total_size : 
                        levels_.begin()->second.total_size;
    }
    
    // Get top N price levels
    std::vector<std::pair<double, double>> get_depth(int levels = 10) const {
        std::vector<std::pair<double, double>> result;
        
        if (is_bid_) {
            // Bids: highest to lowest
            auto it = levels_.rbegin();
            for (int i = 0; i < levels && it != levels_.rend(); ++i, ++it) {
                result.emplace_back(it->first, it->second.total_size);
            }
        } else {
            // Asks: lowest to highest
            auto it = levels_.begin();
            for (int i = 0; i < levels && it != levels_.end(); ++i, ++it) {
                result.emplace_back(it->first, it->second.total_size);
            }
        }
        
        return result;
    }
    
    PriceLevelMap& levels() { return levels_; }
    const PriceLevelMap& levels() const { return levels_; }
    
private:
    bool is_bid_;
    PriceLevelMap levels_;  // Sorted by price
};

// Main matching engine
class MatchingEngine {
public:
    using FillCallback = std::function<void(const Fill&)>;
    using OrderUpdateCallback = std::function<void(const Order&)>;
    
    struct Config {
        double maker_fee_bps;
        double taker_fee_bps;
        double min_order_size;
        double tick_size;
        bool enable_slippage;
        double slippage_bps;
        
        Config() : maker_fee_bps(5.0), taker_fee_bps(10.0), min_order_size(0.0001),
                   tick_size(0.01), enable_slippage(true), slippage_bps(1.0) {}
    };
    
    MatchingEngine(const std::string& product_id, const Config& cfg = {})
        : product_id_(product_id), config_(cfg),
          bids_(true), asks_(false),
          next_order_id_(1), next_fill_id_(1) {}
    
    // Submit order
    // 
    // Parameters:
    //  - client_order_id: client-provided identifier, arbitrary string
    //  - side: BUY or SELL
    //  - type: LIMIT or MARKET (others not fully simulated here)
    //  - price: limit price (ignored for MARKET orders)
    //  - size: requested order size in base units
    //
    // Returns:
    //  - shared_ptr<Order>: engine-managed Order object (owned by engine via orders_ map)
    //
    // Semantics:
    //  - The engine assigns an internal order_id (ORD-<n>) and returns the Order.
    //  - For MARKET orders, the engine will try to consume liquidity immediately.
    //  - For LIMIT orders, the engine will attempt to match against the opposite side
    //    and place any residual size on the book.
    //  - Fees and fills are recorded using add_fill(), callbacks invoked
    //  - The operation is synchronous and returns after matching has been attempted.
    //  - If you call submit_order concurrently from multiple threads, protect the
    //    engine with an external mutex (this implementation is not internally thread-safe).
    std::shared_ptr<Order> submit_order(const std::string& client_order_id,
                                       OrderSide side, OrderType type,
                                       double price, double size) {
        // Generate order ID
        std::string order_id = "ORD-" + std::to_string(next_order_id_++);
        
        auto order = std::make_shared<Order>(
            order_id, client_order_id, product_id_,
            side, type, price, size
        );
        
        // Validate order
        if (size < config_.min_order_size) {
            order->status = OrderStatus::REJECTED;
            if (order_update_callback_) order_update_callback_(*order);
            return order;
        }
        
        // Round price to tick size
        if (type == OrderType::LIMIT) {
            price = std::round(price / config_.tick_size) * config_.tick_size;
            order->price = price;
        }
        
        order->status = OrderStatus::OPEN;
        orders_[order_id] = order;
        
        // Try to match immediately
        if (type == OrderType::MARKET) {
            match_market_order(order);
        } else {
            match_limit_order(order);
        }
        
        // Notify order update
        if (order_update_callback_) order_update_callback_(*order);
        
        return order;
    }
    
    // Cancel order
    //
    // Returns true if cancelled, false otherwise.
    // Notes:
    //  - If the order is already terminal (FILLED/CANCELLED/REJECTED), cancel returns false.
    //  - This is synchronous and will update order state immediately and invoke order_update_callback_.
    bool cancel_order(const std::string& order_id) {
        auto it = orders_.find(order_id);
        if (it == orders_.end()) return false;
        
        auto order = it->second;
        if (!order->is_active()) return false;
        
        // Remove from book
        if (order->side == OrderSide::BUY) {
            bids_.remove_order(order_id);
        } else {
            asks_.remove_order(order_id);
        }
        
        order->status = OrderStatus::CANCELLED;
        order->updated_at = std::chrono::system_clock::now();
        
        if (order_update_callback_) order_update_callback_(*order);
        
        return true;
    }
    
    // Get order by ID
    // - Returns nullptr if not found. The returned shared_ptr points to engine-owned data.
    std::shared_ptr<Order> get_order(const std::string& order_id) const {
        auto it = orders_.find(order_id);
        return (it != orders_.end()) ? it->second : nullptr;
    }
    
    // Get order book snapshot
    // - Returns top N levels for both bids and asks.
    // - Snapshot is a copy (safe to use from other threads) but if you call
    //   get_snapshot() concurrently with submit_order() without external locking,
    //   you may observe in-flight transient states. Consider synchronizing on the
    //   engine when you need a strict point-in-time snapshot.
    struct Snapshot {
        std::vector<std::pair<double, double>> bids;
        std::vector<std::pair<double, double>> asks;
        std::chrono::system_clock::time_point timestamp;
    };

    Snapshot get_snapshot(int depth = 20) const {
        Snapshot snap;
        snap.bids = bids_.get_depth(depth);
        snap.asks = asks_.get_depth(depth);
        snap.timestamp = std::chrono::system_clock::now();
        return snap;
    }
    
    // Register callbacks
    // - set_fill_callback: called for every fill (both maker and taker), executed in the caller
    //   thread that performs the match (synchronous). If the callback performs heavy operations,
    //   offload them to another thread to avoid blocking the matching loop.
    void set_fill_callback(FillCallback cb) { fill_callback_ = cb; }
    void set_order_update_callback(OrderUpdateCallback cb) { order_update_callback_ = cb; }
    
    // Get best bid/ask
    double best_bid() const { return bids_.best_price(); }
    double best_ask() const { return asks_.best_price(); }
    double mid_price() const {
        double bid = best_bid();
        double ask = best_ask();
        return (bid > 0 && ask > 0) ? (bid + ask) / 2.0 : 0.0;
    }
    
private:
    void match_market_order(std::shared_ptr<Order> order) {
        OrderBookSide& opposite_side = (order->side == OrderSide::BUY) ? asks_ : bids_;
        auto& levels = opposite_side.levels();
        
        if (order->side == OrderSide::BUY) {
            // Market buy: match against asks (lowest first)
            for (auto it = levels.begin(); it != levels.end() && order->remaining_size > 1e-8; ) {
                PriceLevel& level = it->second;
                
                while (!level.orders.empty() && order->remaining_size > 1e-8) {
                    std::shared_ptr<Order> resting_order = level.orders.front();
                    double fill_size = std::min(order->remaining_size, resting_order->remaining_size);
                    double fill_price = level.price;
                    
                    // Apply slippage
                    if (config_.enable_slippage) {
                        fill_price *= (1.0 + config_.slippage_bps / 10000.0);
                    }
                    
                    execute_fill(order, resting_order, fill_size, fill_price);
                    
                    if (resting_order->remaining_size <= 1e-8) {
                        level.orders.pop();
                        level.remove_size(fill_size);
                    }
                }
                
                if (level.total_size <= 1e-8) {
                    it = levels.erase(it);
                } else {
                    ++it;
                }
            }
        } else {
            // Market sell: match against bids (highest first)
            for (auto it = levels.rbegin(); it != levels.rend() && order->remaining_size > 1e-8; ++it) {
                PriceLevel& level = it->second;
                
                while (!level.orders.empty() && order->remaining_size > 1e-8) {
                    std::shared_ptr<Order> resting_order = level.orders.front();
                    double fill_size = std::min(order->remaining_size, resting_order->remaining_size);
                    double fill_price = level.price;
                    
                    // Apply slippage
                    if (config_.enable_slippage) {
                        fill_price *= (1.0 - config_.slippage_bps / 10000.0);
                    }
                    
                    execute_fill(order, resting_order, fill_size, fill_price);
                    
                    if (resting_order->remaining_size <= 1e-8) {
                        level.orders.pop();
                        level.remove_size(fill_size);
                    }
                }
            }
        }
        
        // If IOC or FOK, cancel remaining
        if (order->time_in_force == TimeInForce::IOC || 
            order->time_in_force == TimeInForce::FOK) {
            if (order->remaining_size > 1e-8) {
                order->status = OrderStatus::CANCELLED;
            }
        }
    }

    void match_limit_order(std::shared_ptr<Order> order) {
        OrderBookSide& opposite_side = (order->side == OrderSide::BUY) ? asks_ : bids_;
        
        // Check if order can match immediately
        double best_opposite = opposite_side.best_price();
        
        bool can_match = (order->side == OrderSide::BUY) ? 
                        (best_opposite > 0 && order->price >= best_opposite) :
                        (best_opposite > 0 && order->price <= best_opposite);
        
        if (can_match) {
            auto& levels = opposite_side.levels();
            
            if (order->side == OrderSide::BUY) {
                // Aggressive buy limit
                for (auto it = levels.begin(); it != levels.end() && order->remaining_size > 1e-8; ) {
                    if (it->first > order->price) break;
                    
                    PriceLevel& level = it->second;
                    
                    while (!level.orders.empty() && order->remaining_size > 1e-8) {
                        std::shared_ptr<Order> resting_order = level.orders.front();
                        double fill_size = std::min(order->remaining_size, resting_order->remaining_size);
                        
                        execute_fill(order, resting_order, fill_size, level.price);
                        
                        if (resting_order->remaining_size <= 1e-8) {
                            level.orders.pop();
                            level.remove_size(fill_size);
                        }
                    }
                    
                    if (level.total_size <= 1e-8) {
                        it = levels.erase(it);
                    } else {
                        ++it;
                    }
                }
            } else {
                // Aggressive sell limit
                for (auto it = levels.rbegin(); it != levels.rend() && order->remaining_size > 1e-8; ++it) {
                    if (it->first < order->price) break;
                    
                    PriceLevel& level = it->second;
                    
                    while (!level.orders.empty() && order->remaining_size > 1e-8) {
                        std::shared_ptr<Order> resting_order = level.orders.front();
                        double fill_size = std::min(order->remaining_size, resting_order->remaining_size);
                        
                        execute_fill(order, resting_order, fill_size, level.price);
                        
                        if (resting_order->remaining_size <= 1e-8) {
                            level.orders.pop();
                            level.remove_size(fill_size);
                        }
                    }
                }
            }
        }
        
        // Add remaining to book
        if (order->remaining_size > 1e-8 && !order->is_terminal()) {
            if (order->side == OrderSide::BUY) {
                bids_.add_order(order);
            } else {
                asks_.add_order(order);
            }
        }
    }
    
    void execute_fill(std::shared_ptr<Order> taker, std::shared_ptr<Order> maker,
                     double size, double price) {
        // Fees and maker/taker decisions
        double taker_fee = size * price * config_.taker_fee_bps / 10000.0;
        double maker_fee = size * price * config_.maker_fee_bps / 10000.0;

        // Note: The engine charges fees immediately and updates total_fees on orders.
        // If you are simulating exchange accounting you may want to debit user accounts here.

        // Update orders
        taker->add_fill(size, price, taker_fee);
        maker->add_fill(size, price, maker_fee);

        // Create fill objects and invoke callbacks. Callbacks are executed synchronously
        // within the same thread calling submit_order(), so don't make heavy calls in callbacks.
        std::string fill_id = "FILL-" + std::to_string(next_fill_id_++);
        
        Fill taker_fill(fill_id + "-T", taker->order_id, product_id_, 
                       taker->side, price, size, taker_fee, "USD", false);
        Fill maker_fill(fill_id + "-M", maker->order_id, product_id_,
                       maker->side, price, size, maker_fee, "USD", true);
        
        // Notify callbacks
        if (fill_callback_) {
            fill_callback_(taker_fill);
            fill_callback_(maker_fill);
        }
        
        if (order_update_callback_) {
            order_update_callback_(*taker);
            order_update_callback_(*maker);
        }
    }
    
    std::string product_id_;
    Config config_;
    
    OrderBookSide bids_;
    OrderBookSide asks_;
    
    std::map<std::string, std::shared_ptr<Order>> orders_;
    
    uint64_t next_order_id_;
    uint64_t next_fill_id_;
    
    FillCallback fill_callback_;
    OrderUpdateCallback order_update_callback_;
};

} // namespace sim
